server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 100
        min-spare-threads: 25
    port: 8081
#    servlet:
#        context-path: /hotel
management:
    security:
        enables: false
    server:
      port: 81
spring:
    profiles: dubbo
    main:
        allow-bean-definition-overriding: true